{"name": "test_another", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_appium.Testappium object at 0x7fea6e5e5310>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_another(self):\n        \"\"\"Another case...\"\"\"\n>       assert False\nE       assert False\n\ntest_appium.py:117: AssertionError"}, "description": "Another case...", "start": 1626364070753, "stop": 1626364070753, "uuid": "810c7f0f-1484-4a1e-a481-247e90dfec65", "historyId": "ae17c353dec701a569a7af5142c779cb", "testCaseId": "abf8accb956256bab7a1a25b026f20fc", "fullName": "test_appium.Testappium#test_another", "labels": [{"name": "severity", "value": "blocker"}, {"name": "suite", "value": "test_appium"}, {"name": "subSuite", "value": "Testappium"}, {"name": "host", "value": "WKSAR991L.fibertel.com.ar"}, {"name": "thread", "value": "18111-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_appium"}]}